# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Master Of None
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "/_site/index.html" # the subpath of your site, e.g. /blog
url: "http://glister99.github.io" # the base hostname & protocol for your site, e.g. http://example.com

#social:
#  instagram: glister999

#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
theme: jekyll-theme-persephone 
#remote_theme: "mmistakes/jekyll-theme-persephone@0.3.3"
plugins:
  - jekyll-feed


theme_setting:
   # The slides count in the slides layout. Default is 4.
   slides_count: 4
   # The ← back URL on the top of your post page. Default is your site's home page.
   blog_page: "index.markdown" 
   # The URL on your name on the bottom of your post and page. Default is your site's home page.
   about_page: "about.markdown"
   #  The URL of the menu icon(which has three black lines). Will be shown on the slides/book/chapter layouts It won't be shown if blank.
   #archive_page: "archive.md"
   # The nav links on the top right of home/page/post/blog layout. You can set a local page(by setting a layout's path) or and external link ( both title and url are required) here.
   nav_pages:
     - "about.markdown"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
